from __future__ import annotations

from typing import Protocol

from backend.models.api.ledger import CashflowCreate, FeedbackCreate, TransactionCreate
from backend.models.domain.ledger import CashflowRecord, FeedbackRecord, TransactionRecord, UserSettings
from backend.models.domain.portfolio import StockLookup


class LedgerStore(Protocol):
    def read_transactions(self) -> list[TransactionRecord]: ...
    def append_transaction(self, payload: TransactionCreate, *, current_price: float = 0.0) -> TransactionRecord: ...
    def replace_transactions(self, payloads: list[TransactionCreate]) -> int: ...
    def update_transaction(self, tx_id: str, payload: TransactionCreate) -> TransactionRecord: ...
    def delete_transaction(self, tx_id: str) -> None: ...
    def read_cashflows(self) -> list[CashflowRecord]: ...
    def append_cashflow(self, payload: CashflowCreate) -> CashflowRecord: ...
    def replace_cashflows(self, payloads: list[CashflowCreate]) -> int: ...
    def update_cashflow(self, cf_id: str, payload: CashflowCreate) -> CashflowRecord: ...
    def delete_cashflow(self, cf_id: str) -> None: ...
    def read_feedbacks(self) -> list[FeedbackRecord]: ...
    def append_feedback(self, payload: FeedbackCreate) -> FeedbackRecord: ...
    def update_feedback(self, feedback_id: str, payload: FeedbackCreate) -> FeedbackRecord: ...
    def delete_feedback(self, feedback_id: str) -> None: ...
    def get_settings(self) -> UserSettings: ...
    def update_settings(self, settings: UserSettings) -> UserSettings: ...


class StockCatalog(Protocol):
    def read_stocks(self) -> list[StockLookup]: ...
    def search_stocks(self, query: str, *, limit: int = 20) -> list[StockLookup]: ...
    def upsert_stock(self, code: str, name: str) -> None: ...
